"use client";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { motion } from "framer-motion";
import { Scale, FileText, Gavel, ShieldAlert } from "lucide-react";

export default function TermsPage() {
  const provisions = [
    {
      title: "Service Reliability",
      icon: ShieldAlert,
      content: "We provide high-precision engineering on an 'as-available' basis. While we strive for 100% architectural uptime, mission-critical systems require dedicated SLA contracts."
    },
    {
      title: "Intellectual Property",
      icon: FileText,
      content: "All codebase constructs, UI physics, and editorial assets generated by Verve Nova remain our intellectual property until full project settlement."
    },
    {
      title: "Liability Limit",
      icon: Scale,
      content: "Our liability is strictly limited to the value of the specific sprint or milestone currently in execution. We do not accept liability for external infrastructure failures."
    }
  ];

  return (
    <main className="min-h-screen bg-[#0A0A0C]">
      <Navbar />
      
      <section className="pt-48 pb-24 px-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-full h-full bg-violet-600/[0.02] blur-[120px] pointer-events-none" />
        
        <div className="max-w-4xl mx-auto relative z-10 text-center md:text-left">
          <motion.p 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-xs font-black text-white/20 uppercase tracking-[0.5em] mb-6"
          >
            Sovereign // Governance
          </motion.p>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-7xl font-black text-white tracking-tighter uppercase leading-[0.9] mb-12"
          >
            Service <br /> <span className="text-white/10">Terms.</span>
          </motion.h1>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-24">
            {provisions.map((item, i) => (
              <motion.div 
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 + (i * 0.1) }}
                className="glass-card p-8 rounded-3xl border border-white/[0.05] flex flex-col items-center md:items-start text-center md:text-left"
              >
                <item.icon className="w-6 h-6 text-white/30 mb-6" />
                <h3 className="text-sm font-black text-white uppercase tracking-widest mb-4">{item.title}</h3>
                <p className="text-[12px] text-white/30 font-bold leading-relaxed uppercase">{item.content}</p>
              </motion.div>
            ))}
          </div>

          <div className="space-y-12 text-white/20 font-bold uppercase text-[11px] tracking-[0.2em] leading-loose max-w-3xl">
            <p>By engaging with Verve Nova Technologies, you enter into a professional covenant. All project deployments are subject to our 'Surgical Quality Standard'. Any deviation from the agreed-upon technical brief must be authorized through a secondary governance protocol.</p>
            <p>These terms are governed by the laws of India. Any disputes shall be resolved through independent arbitration in alignment with mission-critical industry standards.</p>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
